package com.jer.banyumastourismapp.presentation.ticket

import android.content.res.Configuration.UI_MODE_NIGHT_YES
import android.content.res.Resources
import android.graphics.Bitmap
import androidx.annotation.DrawableRes
import androidx.annotation.StringRes
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.Image
import androidx.compose.foundation.MarqueeDefaults.Spacing
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.scale
import androidx.compose.ui.draw.shadow
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Canvas
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.ColorFilter
import androidx.compose.ui.graphics.DefaultAlpha
import androidx.compose.ui.graphics.Outline
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.PathEffect
import androidx.compose.ui.graphics.Shape
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.graphics.painter.Painter
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.Density
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.LayoutDirection
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.compose.rememberNavController
import coil.compose.AsyncImage
import coil.request.ImageRequest
import coil.transform.Transformation
import com.jer.banyumastourismapp.R
import com.jer.banyumastourismapp.domain.model.Destination
import com.jer.banyumastourismapp.presentation.navgraph.Route
import com.jer.banyumastourismapp.ui.theme.BanyumasTourismAppTheme
import com.simonsickle.compose.barcodes.Barcode
import com.simonsickle.compose.barcodes.BarcodeType

@Composable
fun TicketScreen(modifier: Modifier = Modifier,
                 viewModel: TicketViewModel,
                 navBackToHome: () -> Unit,
                 ) {

//    val shape = TicketShape()

    val userData by viewModel.userData.collectAsState()
    val ticket by viewModel.ticket.collectAsState()
    var idForBarcode by rememberSaveable {
        mutableStateOf("")
    }

    var isGenerated by rememberSaveable {
        mutableStateOf(false)
    }


    val navController = rememberNavController()

    LaunchedEffect(Unit) {
        viewModel.getUserData()
        viewModel.getTicket(userData?.uid ?: "")
    }

    Box(
        modifier = Modifier
            .background(MaterialTheme.colorScheme.primaryContainer)
            .fillMaxSize()
            .padding(start = 30.dp, end = 30.dp, top = 30.dp, bottom = 30.dp)

    ) {

        Column (
            verticalArrangement = Arrangement.Top,
            horizontalAlignment = Alignment.CenterHorizontally,
            modifier = Modifier

        ) {

            Text(
                text = "Your Recent Ticket",
                fontSize = 24.sp,
                color = Color.White,
                fontWeight = FontWeight.Bold
            )

            Spacer(modifier = Modifier.height(15.dp))

            Box(
                contentAlignment = Alignment.TopCenter,
                modifier = Modifier
                    .fillMaxWidth()
                    .clip(MaterialTheme.shapes.extraLarge)
                    .background(Color(0xFFF5FAFB))
            ) {
                Column(
                    verticalArrangement = Arrangement.Top,
                    modifier = Modifier
//                        .fillMaxSize()
                ) {

                    if (ticket?.image != null) {
                        AsyncImage(
                            model = ticket?.image,
                            contentDescription = null,
                            contentScale = ContentScale.Crop,
                            modifier = Modifier
                                .clip(MaterialTheme.shapes.medium)
                                .height(100.dp)
                                .fillMaxWidth()
                        )
                    } else {
                        Image(
                            painter = painterResource(id = R.drawable.viewdefault),
                            contentDescription = null,
                            contentScale = ContentScale.Crop,
                            modifier = Modifier
                                .height(100.dp)
                                .fillMaxWidth()
                        )
                    }

                    Spacer(modifier = Modifier.height(15.dp))
                    Column(
                        horizontalAlignment = Alignment.Start,
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(horizontal = 15.dp)
                    ) {
                        ticket?.category?.let {
                            Box(
                                contentAlignment = Alignment.Center,
                                modifier = Modifier
                                    .clip(RoundedCornerShape(10.dp))
                                    .background(MaterialTheme.colorScheme.primaryContainer)
                                    .padding(horizontal = 10.dp, vertical = 5.dp)
                            ) {
                                Text(
                                    text = it,
                                    fontSize = 12.sp,
                                    color = Color.White
                                )
                            }
                        }
                        Spacer(modifier = Modifier.height(10.dp))

                        ticket?.title?.let {
                            Text(
                                text = it ?: "-",
                                fontSize = 20.sp,
                                maxLines = 2,
                                overflow = TextOverflow.Ellipsis,
                                color = Color(0xFF006874),
                                fontWeight = FontWeight.Bold,
                                modifier = Modifier.fillMaxWidth()
                            )
                        }


                        Spacer(modifier = Modifier.height(10.dp))

                        Row() {

                            //date
                            Column(
                                horizontalAlignment = Alignment.Start,
                                modifier = Modifier
                                    .weight(1f)
                            ) {
                                Text(
                                    text = "Date",
                                    fontSize = 12.sp,
                                    color = Color.DarkGray
                                )

                                Spacer(modifier = Modifier.height(10.dp))

                                ticket?.date?.let {
                                    Text(
                                        text = it ?: "-",
                                        fontSize = 12.sp,
                                        fontWeight = FontWeight.Medium,
                                        color = Color.Black
                                    )
                                }
                            }

                            Spacer(modifier = Modifier.width(10.dp))

                            //price
                            Column(
                                horizontalAlignment = Alignment.Start,
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .weight(1f)
                            ) {
                                Text(
                                    text = "Total Price",
                                    fontSize = 12.sp,
                                    color = Color.DarkGray
                                )

                                Spacer(modifier = Modifier.height(10.dp))

                                ticket?.price?.let {
                                    Text(
                                        text = it.toString(),
                                        fontSize = 12.sp,
                                        fontWeight = FontWeight.Medium,
                                        color = Color.Black
                                    )
                                }
                            }

                            Spacer(modifier = Modifier.width(10.dp))

                            //qty
                            Column(
                                horizontalAlignment = Alignment.Start,
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .weight(1f)
                            ) {
                                Text(
                                    text = "Qty",
                                    fontSize = 12.sp,
                                    color = Color.DarkGray
                                )

                                Spacer(modifier = Modifier.height(10.dp))

                                ticket?.qty?.let {
                                    Text(
                                        text = it.toString(),
                                        fontSize = 12.sp,
                                        fontWeight = FontWeight.Medium,
                                        color = Color.Black
                                    )
                                }
                            }

                        }

                        Spacer(modifier = Modifier.height(10.dp))

                        Row() {

                            //name
                            Column(
                                horizontalAlignment = Alignment.Start,
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .weight(1f)
                            ) {
                                Text(
                                    text = "Name",
                                    fontSize = 12.sp,
                                    color = Color.DarkGray

                                )

                                Spacer(modifier = Modifier.height(10.dp))

                                ticket?.name?.let {
                                    Text(
                                        text = it ?: "-",
                                        fontSize = 12.sp,
                                        maxLines = 2,
                                        overflow = TextOverflow.Ellipsis,
                                        fontWeight = FontWeight.Medium,
                                        color = Color.Black
                                    )
                                }
                            }

                            Spacer(modifier = Modifier.width(10.dp))

                            //id
                            Column(

                                horizontalAlignment = Alignment.Start,
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .weight(1f)
                            ) {
                                Text(
                                    text = "ID",
                                    fontSize = 12.sp,
                                    color = Color.DarkGray
                                )

                                Spacer(modifier = Modifier.height(10.dp))

                                ticket?.id?.let {
                                    Text(
                                        text = "BMT00${it} - ${ticket?.createdAt}" ?: "-",
                                        fontSize = 12.sp,
                                        fontWeight = FontWeight.Medium,
                                        color = Color.Black
                                    )
                                }


                            }

                            Spacer(modifier = Modifier.width(10.dp))

                            Box(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .weight(1f)
                            )

                        }


                    }

                    Spacer(modifier = Modifier.height(10.dp))

                    //location
                    Column(
                        horizontalAlignment = Alignment.Start,
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(horizontal = 15.dp)
                    ) {
                        Text(
                            text = "Location",
                            fontSize = 12.sp,
                            color = Color.DarkGray
                        )

                        Spacer(modifier = Modifier.height(10.dp))

                        ticket?.location?.let {
                            Text(
                                text = it,
                                fontSize = 12.sp,
                                fontWeight = FontWeight.Medium,
                                color = Color.Black
                            )
                        }
                    }

                    Spacer(modifier = Modifier.height(20.dp))

                    DashLineSpacer(modifier = Modifier.fillMaxWidth())

                    Spacer(modifier = Modifier.height(10.dp))

                    Box(
                        modifier = Modifier
                            .height(250.dp)
                            .padding(start = 30.dp, end = 30.dp, bottom = 15.dp)
                    ) {
                        if ( isGenerated) {
                            Barcode(
                                type = BarcodeType.QR_CODE,
                                value = idForBarcode,
                                resolutionFactor = 10,
                                modifier = Modifier
                                    .fillMaxSize()
                            )
                        } else {
                            Text("QR code not available", fontSize = 16.sp, color = Color.Black)
                        }
//                    if (!BarcodeType.QR_CODE.isValueValid(idForBarcode)) {
//                        Text("this code is not compatible")
//                    }
                    }

                }

            }

            Spacer(modifier = Modifier.height(15.dp))


            var refreshText by rememberSaveable {
                mutableStateOf("Refresh Ticket")
            }
            var refreshClick by rememberSaveable {
                mutableStateOf(false)
            }
            Row ( horizontalArrangement = Arrangement.Center, modifier = Modifier.fillMaxWidth()) {
                OutlinedButton(
                    modifier = Modifier
                        .weight(1f),
                    shape = MaterialTheme.shapes.medium,
                    colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.outline.copy(alpha = 0.5f)),
                    border = BorderStroke(2.dp, MaterialTheme.colorScheme.outline),
                    onClick = { navBackToHome()}
                ) {

                    Text(text = "Back To Home", color = Color.White, fontSize = 14.sp)

                }

                Spacer(modifier = Modifier.width(15.dp))

                Button(
                    modifier = Modifier
                        .weight(1f),
                    shape = MaterialTheme.shapes.medium,
                    colors = ButtonDefaults.buttonColors(containerColor = Color.White),
                    onClick = {
                        viewModel.getTicket(userData?.uid ?: "")
                        refreshClick = true
                        if (ticket != null) {
                            isGenerated = true
                            idForBarcode = "BMT00${ticket?.id} - ${ticket?.createdAt}"
                        }
                    }
                ) {

                    Text(text = refreshText, color = Color.Black, fontSize = 14.sp)

                }


                if (refreshClick) refreshText = "Generate QR"

            }


        }

    }
}


@Composable
fun DashLineSpacer(modifier: Modifier = Modifier) {
    val color = MaterialTheme.colorScheme.primaryContainer
    val colorLine = Color.Gray
    androidx.compose.foundation.Canvas(modifier.height(10.dp)) {
        val dashLength = 4.dp.toPx()
        val gapLength = 4.dp.toPx()
        val pathEffect = PathEffect.dashPathEffect(floatArrayOf(dashLength, gapLength), 0f)
        val halfHeight = size.height / 2f
        drawLine(
            color = colorLine,
            pathEffect = pathEffect,
            strokeWidth = 3.dp.toPx(),
            start = Offset(0f, halfHeight),
            end = Offset(size.width, halfHeight)
        )
        drawCircle(
            color = color,
            radius = 50f,
            center = Offset(0f, halfHeight)
        )

        drawCircle(
            color = color,
            radius = 50f,
            center = Offset(size.width, halfHeight)
        )
    }
}




//    @Preview(showBackground = true)
//    @Preview(showBackground = true, uiMode = UI_MODE_NIGHT_YES)
//    @Composable
//    private fun PrevTicketScreen() {
//        BanyumasTourismAppTheme {
//            TicketScreen()
//        }
//    }
